merging mq demo app
ibm-messaging/mq-dev-patterns pull request #105
Opened 2023-01-19 11:35 UTC by rin0o1

2023-01-19 11:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ibm-messaging/mq-dev-patterns?pullRequest=105) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ibm-messaging/mq-dev-patterns?pullRequest=105) before we can accept your contribution.<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ibm-messaging/mq-dev-patterns?pullRequest=105) it.</sub>

2023-01-19 11:47 UTC, chughts requested changes
Please review and accept the CLA. 

Some files can be removed from the pull request.

2023-01-19 11:49 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/CONTRIBUTING.md
> +
Contributing file should be at mq-dev-patterns root.

2023-01-19 11:50 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/LICENSE
> +                                 Apache License
This a duplicate of the license at the root of the dev-patterns repository. Can be removed from here.

2023-01-19 11:55 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/QMGR-docker-compose.yml
> +      - MQ_APP_PASSWORD=${APP_PASSWORD}
use the syntax ${APP_PASSWORD:?err} to signal failure when password has not been provided.

2023-01-19 11:58 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/QMGR-docker-compose.yml
> +services:
Only include the yml files that the tutorial or the readme refer to

2023-01-19 11:59 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/README.md
> +IBM MQ MESSAGING PLAYGROUND APPLICATION
Add a link to the tutorial (or a placeholder) to remind you to.

2023-01-19 12:02 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/backend/AWS-showcase-backend/keys/clientkey.sth
> +n��P��]������}�F�K��ȭq��K30Pu�dl4���%a�����P���k�rz�N9�	&�����Ц�E&�z	?8��V,�p=�rN����<&�SP�eӫ}�e&�q�
these files should be removed.

2023-01-19 12:04 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/frontend/AWS-MQ-showcase/.circleci/config.yml
> +version: 2
These look like editor configurations that shouldn't be included in this pull request.

2023-01-19 12:05 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/frontend/AWS-MQ-showcase/.editorconfig
> +# top-most EditorConfig file
unneeded editor configuration.

2023-01-19 12:05 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/frontend/AWS-MQ-showcase/.github/CODE_OF_CONDUCT.md
> +## Carbon Code of Conduct
Should be at root of dev-patterns.

2023-01-19 12:06 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/frontend/AWS-MQ-showcase/.github/CODE_OF_CONDUCT.md
> +## Carbon Code of Conduct
just 
## Code of Conduct

2023-01-19 12:07 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/frontend/AWS-MQ-showcase/.github/CODE_OF_CONDUCT.md
> +5. `#carbon-components`: This channel is for questions about Carbon Components only. It is not the place to ask general coding questions. Instead, use a dev community like [StackOverflow](https://sta
dev-patterns specific

2023-01-19 12:07 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/frontend/AWS-MQ-showcase/.github/CONTRIBUTING.md
> +# Contribution Guidelines
into the root dev-patterns, and dev-patterns specific.

2023-01-19 12:08 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/frontend/AWS-MQ-showcase/.github/ISSUE_TEMPLATE/bug_report.md
> +---
dev-patterns specific into dev-patterns root.

2023-01-19 12:08 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/frontend/AWS-MQ-showcase/.github/ISSUE_TEMPLATE/feature_request.md
> +---
dev-patterns specify into dev-patterns root.

2023-01-19 12:09 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/frontend/AWS-MQ-showcase/.github/PULL_REQUEST_TEMPLATE.md
> +Closes #
dev-patterns root.

2023-01-19 12:09 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/frontend/AWS-MQ-showcase/.github/SUPPORT.md
> +# Support
dev-patterns root.

2023-01-19 12:09 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/frontend/AWS-MQ-showcase/.npmrc
> +registry=https://registry.npmjs.org
not needed.

2023-01-19 12:09 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/frontend/AWS-MQ-showcase/.prettierignore
> +node_modules
not needed

2023-01-19 12:11 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/frontend/AWS-MQ-showcase/package.json
> +  "repository": "git@github.com:carbon-design-system/carbon-tutorial.git",
correct repository

2023-01-19 12:12 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/frontend/AWS-MQ-showcase/public/index.html
> +<!DOCTYPE html>
Need Copyright

2023-01-19 12:16 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/frontend/AWS-MQ-showcase/src/components/MQPatterns/RequestResponse/nodes.js
> +  // {
These ids will clash with the other pattern. Suggest you prefix with the pattern eg. "RR01" etc.

2023-01-19 12:20 UTC, chughts requested changes
see comments above.

2023-01-19 15:09 UTC, chughts approved these changes

2023-01-19 15:09 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/LICENSE
> +                                 Apache License
This is a duplicate of the LICENSE at the root of dev-patterns. This one can be removed.

2023-01-26 11:51 UTC, rcoppen approved these changes

2023-01-26 12:02 UTC, merged