Spring-JMS migration to Jakarta
ibm-messaging/mq-dev-patterns pull request #140
Opened 2023-05-17 14:21 UTC by rin0o1

2023-05-17 14:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ibm-messaging/mq-dev-patterns?pullRequest=140) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ibm-messaging/mq-dev-patterns?pullRequest=140) before we can accept your contribution.<br/><hr/>**francescorinaldidev@gmail.com** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ibm-messaging/mq-dev-patterns?pullRequest=140) it.</sub>

2023-05-17 14:39 UTC, chughts requested changes
Nothing from the target directory should be included.

2023-05-17 14:39 UTC, chughts commented on Spring-JMS/target/classes/application.properties
Nothing from the target directory should be included in this repository,.

2023-05-17 14:39 UTC, chughts commented on Spring-JMS/target/maven-archiver/pom.properties
nothing from target ...

2023-05-17 14:44 UTC, chughts approved these changes
Approved subject to signing the CLA.

2023-05-18 07:17 UTC, chughts commented
@rin0o1 Seems like something is amiss with the CLA webhook. Can you confirm that you have read and signed the CLA?

2023-05-18 08:17 UTC, rin0o1 commented
CLA signed

2023-05-18 08:17 UTC, merged