Upgrading from Spring Boot 2 to Spring Boot 3
ibm-messaging/mq-dev-patterns pull request #207
Opened 2024-02-19 11:07 UTC by tanaysingh3484

I have made the required changes which were updating the copyright years of only those files which we updated and reverting the remaining back to their original values. Also updated a few secrets back to their original values which were missed out in the previous commits. Finally removed the target folder from the commit.

2024-02-19 11:44 UTC, chughts requested changes

2024-02-19 11:44 UTC, chughts commented on Spring-JMS/src/main/java/com/ibm/mq/samples/jms/spring/globals/properties/MQAdminProperties.java
> +    //Uncomment the below lines when connecting to MQ on the cloud
Uncomment when connecting to MQ using TLS

2024-02-19 11:44 UTC, chughts commented on Spring-JMS/src/main/java/com/ibm/mq/samples/jms/spring/level113/MQConfiguration113.java
> +@Configuration
Should be disabled by default.

2024-02-19 11:44 UTC, chughts commented on Spring-JMS/src/main/java/com/ibm/mq/samples/jms/spring/level114/MQConfiguration114.java
> +        // Uncomment when running the 114 sample
Configuration should not be hardcoded. Remove these lines, even if they are only comments.

2024-02-19 11:44 UTC, chughts commented on Spring-JMS/src/main/java/com/ibm/mq/samples/jms/spring/level115/MQConfiguration115.java
> +            //Uncomment the below lines and in MQAdminProperties.java when connecting to MQ on the cloud
When connecting to MQ using TLS.

2024-02-19 11:44 UTC, chughts commented on Spring-JMS/src/main/resources/application.properties
> +#Uncomment the below lines when connecting to MQ on Cloud
When connecting to MQ using TLS.

2024-02-19 11:44 UTC, chughts commented on Spring-JMS/src/main/resources/application.properties
> +#Uncomment the below lines when connecting to MQ on Cloud
When connecting the MQ using TLS.

2024-02-19 12:03 UTC, tanaysingh3484 commented
I have made the required changes.

2024-02-19 12:12 UTC, chughts commented
You made some of the suggested changes, not all of them. Please review all "Requested Changes" in this thread.

2024-02-19 12:15 UTC, chughts approved these changes

2024-02-26 16:41 UTC, rcoppen approved these changes

2024-02-26 16:42 UTC, merged