Cleaned docker files
ibm-messaging/mq-dev-patterns pull request #225
Opened 2024-03-25 10:54 UTC by harshitsharma2801

1) Cleaned docker files for both frontend and backend to have separate build and runtime stage.
2)Bumped carbon
3)The logic to increase the number of tickets in point-to-point and req-res had a small bug , fixed that.

2024-03-26 09:39 UTC, harshitsharma2801 commented
Fixed the Pub/Sub UI to display the required components in the sidebar.

2024-03-26 12:19 UTC, chughts requested changes

2024-03-26 12:19 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/backend/Dockerfile
>  FROM ubuntu:20.04 as builder
As we are building a node.js image, is there a node.js base image that would the need to install node etc. ?

2024-03-26 12:19 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/frontend/AWS-MQ-showcase/package.json
> +    "start": "BROWSER=none react-scripts start",
Need to add explanation of why this is necessary for WSL.

2024-03-26 12:19 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/frontend/nginx.conf
> +        proxy_pass http://be:8080/api/;
Http / Https, Host and port need to be set via the environment variables:

````
const be = process.env.REACT_APP_BE_HOST;
const be_port = process.env.REACT_APP_BE_PORT || "8080";

const be_tls = process.env.REACT_APP_BE_TLS || false;
const HTTP_PROTOCOL = be_tls ? "https://" : "http://";
````

See existing proxy setup : https://github.com/ibm-messaging/mq-dev-patterns/blob/2b66777a8208e149bea3c3e24da435fa7b14ae58/ibm-messaging-mq-cloud-showcase-app/frontend/AWS-MQ-showcase/src/setupProxy.js#L19

2024-04-02 11:03 UTC, chughts requested changes

2024-04-02 11:03 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/frontend/AWS-MQ-showcase/src/setupProxy.js
>  const { createProxyMiddleware } = require('http-proxy-middleware');
Update copyright date

2024-04-02 11:03 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/frontend/Dockerfile
> +#  Copyright 2022, 2023, 2024 IBM Corp.
fix copyright date

2024-04-02 11:03 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/frontend/nginx.conf
> +        proxy_pass http://be:8080/api/;
should this code be using `be_port` in stead of 8080 ?

2024-04-03 09:19 UTC, chughts requested changes
Only update the copyright on files that have changed. Many of the files in this pull request are showing the only change as the copyright line. 

If a file has been updated the format should be 

```Copyright 2022, 2024 IBM Corp.````

Note the spacing. 1st date is when the file was initially created, 2nd date is when the last modifications were made to the file.

2024-04-03 09:19 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/backend/Dockerfile
> +FROM node:20.9.0 as builder
The build is at 20.9.0, yet the runtime is at 18-slim, these should be aligned.

2024-04-03 09:19 UTC, chughts commented on ibm-messaging-mq-cloud-showcase-app/frontend/Dockerfile
> +#  Copyright 2022 , 2024 IBM Corp.
remove space between 2022 and ,

2024-04-03 10:27 UTC, chughts approved these changes

2024-04-03 10:29 UTC, merged