Unit test case for the basicget.js
ibm-messaging/mq-dev-patterns pull request #234
Opened 2024-04-19 09:28 UTC by tanaysingh3484

Created a Unit-test file for the `basicget.js` file, using the `Chai` assertion library.

2024-05-01 13:42 UTC, chughts requested changes

2024-05-01 13:42 UTC, chughts commented on Node.js/test/basicget.test.js
> +const { buildMQDetails, ccdtCheck, initialise, connx, open, close, disconnect, getMessage } = require('../basicget');
README needs updating with instructions on how to run the tests.

2024-05-01 13:42 UTC, chughts commented on Node.js/test/basicget.test.js
> +const { buildMQDetails, ccdtCheck, initialise, connx, open, close, disconnect, getMessage } = require('../basicget');
package.json will need updating to allow for `npm test` command

2024-05-01 13:42 UTC, chughts commented on Node.js/test/basicget.test.js
> +            await buildMQDetails(MQDetails, credentials, i);
This is a copy and paste of the put logic. Instead, just run `basicput`, then test that the get functions run.

2024-05-02 08:30 UTC, tanaysingh3484 commented
- Updated the `MQGET` test by adding an `exec` statement to first execute the `basicput.js` file, following which the `getMessage` function is called
- Added a `README` for the test directory, which contains the information needed to run these testcases
- Updated the `basicget.js` with the required `module.exports`.

2024-05-07 15:00 UTC, chughts approved these changes
Seems odd to export the functions, just so they can be tested, but I guess this is a result of having a single module node.js app.

2024-05-07 15:01 UTC, merged