Azure serverless sample application
ibm-messaging/mq-dev-patterns pull request #87
Opened 2022-07-13 10:33 UTC by aslihanilgin

- Added Azure Function sample application to demonstrate MQ serverless applications on Azure
- Corrected typos in AWS Lambda serverless application README.md

2022-07-13 11:00 UTC, chughts requested changes

2022-07-13 11:24 UTC, aslihanilgin commented
@chughts Requested changes made.

2022-07-13 13:22 UTC, chughts commented on serverless/azure-functions-rest-http-trigger/.azure/.local_context_aslihanilginokan
> +; This file is used to store persistent parameters.
This file is currently still part of the pull request.

2022-07-13 13:23 UTC, chughts commented on serverless/azure-functions-rest-http-trigger/.vscode/settings.json
> +{
These files are still part of the pull request.

2022-07-13 13:25 UTC, chughts commented on serverless/azure-functions-rest-http-trigger/README.md
> +These REST samples are written in Node.js and have been tested with Azure Functions runtime of `Node.js`.
A version of 16 contradicts the version 14 as specified in serverless/aws-lambda-rest/README.md

2022-07-13 13:27 UTC, chughts commented
@aslihanilgin The hidden files need to be removed from the pull request. Updates to the .gitignore only apply to new files that you don't wish to commit, and not to files you have already committed.

2022-07-13 17:29 UTC, aslihanilgin commented
Working on removing the sensitive and unneeded files

2022-07-20 10:20 UTC, aslihanilgin commented on serverless/azure-functions-rest-http-trigger/.azure/.local_context_aslihanilginokan
> +; This file is used to store persistent parameters.
This is now removed.

2022-07-20 10:20 UTC, aslihanilgin commented on serverless/azure-functions-rest-http-trigger/.vscode/settings.json
> +{
Now removed.

2022-07-26 09:57 UTC, chughts commented on serverless/azure-functions-rest-http-trigger/README.md
> +These REST samples are written in Node.js and have been tested with Azure Functions runtime of `Node.js`.
This conflict is still present. 

serverless/azure-functions-rest-http-trigger/README.md

> These REST samples are written in Node.js and have been tested with a Azure Functions runtime of `Node.js v16`.

serverless/aws-lambda-rest/README.md

> These REST samples are written in Node.js and have been tested with
>  a SAM AWS Lambda runtime of `nodejs14.x`

.

2022-07-26 09:58 UTC, chughts commented on serverless/azure-functions-rest-http-trigger/README.md
> +These REST samples are written in Node.js and have been tested with Azure Functions runtime of `Node.js`.
AWS-lambda is not part of this pull request!

2022-07-26 10:00 UTC, chughts commented on serverless/azure-functions-rest-http-trigger/lib/mqrestapi.js
> +      console.log('https://' + options.host + options.path);
debug would be better than console.log

2022-07-26 10:01 UTC, chughts commented
Please change the console.log logging to debug logging.

2022-07-26 10:17 UTC, aslihanilgin commented
Changed console.log logging to debug logging.

2022-07-26 10:43 UTC, merged